spring:
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    adresses: localhost
    username: admin
    password: admin
#    addresses: node1.rabbitmq.dev.intranet.pags,node2.rabbitmq.dev.intranet.pags,node3.rabbitmq.dev.intranet.pags
#    username: card_account_api
#    virtual-host: /card_account
#    password: "{!oc1h%c&z7cu!t"
  task:
    execution:
      pool:
        core-size: 10
        max-size: 200
        queue-capacity: 1
      shutdown:
        await-termination: true
        await-termination-period: 20s
  data:
    mongodb:
      url: mongodb://localhost:27017
