spring:
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    adresses: localhost
    username: admin
    password: admin
  data:
    mongodb:
      url: mongodb://localhost:27017

  cloud:
    stream:
      bindings:
        rabbitData-out-0:
          destination: ha_ac_cloud_stream_exchange_notify_create_transaction_tecban
          contentType: application/json
          producer:
            requiredGroups: ha_ac_cloud_stream_queue_notify_create_transaction_tecban
      default:
        producer:
          errorChannelEnabled: true
      rabbit:
        default:
          producer:
            exchangeType: fanout
            useConfirmHeader: true
            queueNameGroupOnly: true
            quorum:
              enabled: true
              initialQuorumSize: 3
